[project]
name = "unipressed"
version = "1.4.0"
description = "Comprehensive Python client for the Uniprot REST API"
authors = [{name = "Michael Milton", email = "michael.r.milton@gmail.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.28.1",
    "typing-extensions>=4.3.0",
]

[project.urls]
Homepage = "https://multimeric.github.io/Unipressed"
Repository = "https://github.com/multimeric/Unipressed"

[project.optional-dependencies]
tests = [
    "pytest>=7.1.2",
    "fastaparser>=1.1",
]
docs = [
    "mkdocstrings[python]>=0.25.2",
    "mkdocs>=1.6.0",
    "mkdocs-material>=9.5.31",
    "mkdocs-include-markdown-plugin>=6.2.2",
    "rich>=13.7.1",
]
readme = [
    "jupyter>=1.0.0",
]
lint = [
    "pre-commit>=2.20.0",
    "types-requests>=2.28.7",
]
codegen = [
    "typer>=0.6.1",
    "inflection>=0.5.1",
    "black>=22.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.isort]
profile = "black"

[tool.mypy]
disable_error_code = "misc"
show_error_codes = true
files = "unipressed/"

[tool.pyright]
reportUnknownParameterType = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportMissingTypeArgument = false
reportPrivateUsage = false