from typing import Union
from typing_extensions import TypeAlias, Literal, TypedDict, NotRequired
from dataclasses import dataclass, field
from datetime import date
import uniprot_rest

Existence: TypeAlias = Literal["1", "2", "3", "4", "5"]
Organelle: TypeAlias = Literal[
    "mitochondrion",
    "plastid",
    "chloroplast",
    "cyanelle",
    "apicoplast",
    "organellar chromatophore",
    "non-photosynthetic plastid",
    "nucleomorph",
    "hydrogenosome",
]
UniprotkbQuery: TypeAlias = TypedDict(
    "UniprotkbQuery",
    {
        "accession_field": NotRequired[str],
        "id_field": NotRequired[str],
        "protein_name_field": NotRequired[str],
        "gene_field": NotRequired[str],
        "organism_name_field": NotRequired[str],
        "taxonomy_name": NotRequired[str],
        "virus_host_name": NotRequired[str],
        "existence": NotRequired[Existence],
        "ec": NotRequired[str],
        "cc_cofactor_chebi": NotRequired[str],
        "ccev_cofactor_chebi": NotRequired[str],
        "cc_cofactor_note": NotRequired[str],
        "ccev_cofactor_note": NotRequired[str],
        "cc_bpcp": NotRequired[str],
        "ccev_bpcp": NotRequired[str],
        "cc_bpcp_absorption": NotRequired[str],
        "ccev_bpcp_absorption": NotRequired[str],
        "cc_bpcp_kinetics": NotRequired[str],
        "ccev_bpcp_kinetics": NotRequired[str],
        "cc_bpcp_ph_dependence": NotRequired[str],
        "ccev_bpcp_ph_dependence": NotRequired[str],
        "cc_bpcp_redox_potential": NotRequired[str],
        "ccev_bpcp_redox_potential": NotRequired[str],
        "cc_bpcp_temp_dependence": NotRequired[str],
        "ccev_bpcp_temp_dependence": NotRequired[str],
        "cc_catalytic_activity_field": NotRequired[str],
        "ccev_catalytic_activity": NotRequired[str],
        "cc_activity_regulation": NotRequired[str],
        "ccev_activity_regulation": NotRequired[str],
        "cc_function": NotRequired[str],
        "ccev_function": NotRequired[str],
        "cc_caution": NotRequired[str],
        "ccev_caution": NotRequired[str],
        "ft_sites": NotRequired[str],
        "ftlen_sites": NotRequired[int],
        "ftev_sites": NotRequired[str],
        "ft_act_site": NotRequired[str],
        "ftlen_act_site": NotRequired[int],
        "ftev_act_site": NotRequired[str],
        "ft_metal": NotRequired[str],
        "ftlen_metal": NotRequired[int],
        "ftev_metal": NotRequired[str],
        "ft_binding": NotRequired[str],
        "ftlen_binding": NotRequired[int],
        "ftev_binding": NotRequired[str],
        "ft_site": NotRequired[str],
        "ftlen_site": NotRequired[int],
        "ftev_site": NotRequired[str],
        "ft_ca_bind": NotRequired[str],
        "ftlen_ca_bind": NotRequired[int],
        "ftev_ca_bind": NotRequired[str],
        "ft_dna_bind": NotRequired[str],
        "ftlen_dna_bind": NotRequired[int],
        "ftev_dna_bind": NotRequired[str],
        "ft_np_bind": NotRequired[str],
        "ftlen_np_bind": NotRequired[int],
        "ftev_np_bind": NotRequired[str],
        "cc_pathway": NotRequired[str],
        "ccev_pathway": NotRequired[str],
        "cc_miscellaneous": NotRequired[str],
        "ccev_miscellaneous": NotRequired[str],
        "cc_scl_term_field": NotRequired[str],
        "ccev_scl_term": NotRequired[str],
        "cc_scl_note": NotRequired[str],
        "ccev_scl_note": NotRequired[str],
        "ft_transmem": NotRequired[str],
        "ftlen_transmem": NotRequired[int],
        "ftev_transmem": NotRequired[str],
        "ft_topo_dom": NotRequired[str],
        "ftlen_topo_dom": NotRequired[int],
        "ftev_topo_dom": NotRequired[str],
        "ft_intramem": NotRequired[str],
        "ftlen_intramem": NotRequired[int],
        "ftev_intramem": NotRequired[str],
        "cc_disease": NotRequired[str],
        "ccev_disease": NotRequired[str],
        "cc_allergen": NotRequired[str],
        "ccev_allergen": NotRequired[str],
        "cc_toxic_dose": NotRequired[str],
        "ccev_toxic_dose": NotRequired[str],
        "cc_biotechnology": NotRequired[str],
        "ccev_biotechnology": NotRequired[str],
        "cc_pharmaceutical": NotRequired[str],
        "ccev_pharmaceutical": NotRequired[str],
        "cc_disruption_phenotype": NotRequired[str],
        "ccev_disruption_phenotype": NotRequired[str],
        "ft_mutagen": NotRequired[str],
        "ftlen_mutagen": NotRequired[int],
        "ftev_mutagen": NotRequired[str],
        "cc_ptm": NotRequired[str],
        "ccev_ptm": NotRequired[str],
        "ft_mod_res": NotRequired[str],
        "ftlen_mod_res": NotRequired[int],
        "ftev_mod_res": NotRequired[str],
        "ft_lipid": NotRequired[str],
        "ftlen_lipid": NotRequired[int],
        "ftev_lipid": NotRequired[str],
        "ft_carbohyd": NotRequired[str],
        "ftlen_carbohyd": NotRequired[int],
        "ftev_carbohyd": NotRequired[str],
        "ft_disulfid": NotRequired[str],
        "ftlen_disulfid": NotRequired[int],
        "ftev_disulfid": NotRequired[str],
        "ft_crosslnk": NotRequired[str],
        "ftlen_crosslnk": NotRequired[int],
        "ftev_crosslnk": NotRequired[str],
        "ft_molecule_processing": NotRequired[str],
        "ftlen_molecule_processing": NotRequired[int],
        "ftev_molecule_processing": NotRequired[str],
        "ft_chain": NotRequired[str],
        "ftlen_chain": NotRequired[int],
        "ftev_chain": NotRequired[str],
        "ft_init_met": NotRequired[str],
        "ftlen_init_met": NotRequired[int],
        "ftev_init_met": NotRequired[str],
        "ft_peptide": NotRequired[str],
        "ftlen_peptide": NotRequired[int],
        "ftev_peptide": NotRequired[str],
        "ft_signal": NotRequired[str],
        "ftlen_signal": NotRequired[int],
        "ftev_signal": NotRequired[str],
        "ft_propep": NotRequired[str],
        "ftlen_propep": NotRequired[int],
        "ftev_propep": NotRequired[str],
        "ft_transit": NotRequired[str],
        "ftlen_transit": NotRequired[int],
        "ftev_transit": NotRequired[str],
        "cc_developmental_stage": NotRequired[str],
        "ccev_developmental_stage": NotRequired[str],
        "cc_induction": NotRequired[str],
        "ccev_induction": NotRequired[str],
        "cc_tissue_specificity": NotRequired[str],
        "ccev_tissue_specificity": NotRequired[str],
        "interactor": NotRequired[str],
        "cc_subunit": NotRequired[str],
        "ccev_subunit": NotRequired[str],
        "structure_3d": NotRequired[bool],
        "ft_secstruct": NotRequired[str],
        "ftlen_secstruct": NotRequired[int],
        "ftev_secstruct": NotRequired[str],
        "ft_helix": NotRequired[str],
        "ftlen_helix": NotRequired[int],
        "ftev_helix": NotRequired[str],
        "ft_turn": NotRequired[str],
        "ftlen_turn": NotRequired[int],
        "ftev_turn": NotRequired[str],
        "ft_strand": NotRequired[str],
        "ftlen_strand": NotRequired[int],
        "ftev_strand": NotRequired[str],
        "mass_range": NotRequired[int],
        "length_range": NotRequired[int],
        "cc_ap": NotRequired[str],
        "ccev_ap": NotRequired[str],
        "cc_ap_apu": NotRequired[str],
        "ccev_ap_apu": NotRequired[str],
        "cc_ap_as": NotRequired[str],
        "ccev_ap_as": NotRequired[str],
        "cc_ap_ai": NotRequired[str],
        "ccev_ap_ai": NotRequired[str],
        "cc_ap_rf": NotRequired[str],
        "ccev_ap_rf": NotRequired[str],
        "cc_sequence_caution": NotRequired[str],
        "ccev_sequence_caution": NotRequired[str],
        "cc_sc_framesh": NotRequired[str],
        "cc_sc_einit": NotRequired[str],
        "cc_sc_eterm": NotRequired[str],
        "cc_sc_epred": NotRequired[str],
        "cc_sc_etran": NotRequired[str],
        "cc_sc_misc": NotRequired[str],
        "ccev_sc_misc": NotRequired[str],
        "cc_mass_spectrometry": NotRequired[str],
        "ccev_mass_spectrometry": NotRequired[str],
        "cc_polymorphism": NotRequired[str],
        "ccev_polymorphism": NotRequired[str],
        "cc_rna_editing": NotRequired[str],
        "ccev_rna_editing": NotRequired[str],
        "ft_variants": NotRequired[str],
        "ftlen_variants": NotRequired[int],
        "ftev_variants": NotRequired[str],
        "ft_variant": NotRequired[str],
        "ftlen_variant": NotRequired[int],
        "ftev_variant": NotRequired[str],
        "ft_var_seq": NotRequired[str],
        "ftlen_var_seq": NotRequired[int],
        "ftev_var_seq": NotRequired[str],
        "ft_non_std": NotRequired[str],
        "ftlen_non_std": NotRequired[int],
        "ftev_non_std": NotRequired[str],
        "ft_non_ter": NotRequired[str],
        "ftlen_non_ter": NotRequired[int],
        "ftev_non_ter": NotRequired[str],
        "ft_non_cons": NotRequired[str],
        "ftlen_non_cons": NotRequired[int],
        "ftev_non_cons": NotRequired[str],
        "ft_conflict": NotRequired[str],
        "ftlen_conflict": NotRequired[int],
        "ftev_conflict": NotRequired[str],
        "ft_unsure": NotRequired[str],
        "ftlen_unsure": NotRequired[int],
        "ftev_unsure": NotRequired[str],
        "ft_positional": NotRequired[str],
        "ftlen_positional": NotRequired[int],
        "ftev_positional": NotRequired[str],
        "fragment": NotRequired[bool],
        "organelle": NotRequired[Organelle],
        "precursor": NotRequired[bool],
        "tissue": NotRequired[str],
        "strain": NotRequired[str],
        "plasmid": NotRequired[str],
        "transposon": NotRequired[str],
        "ft_domain": NotRequired[str],
        "ftlen_domain": NotRequired[int],
        "ftev_domain": NotRequired[str],
        "cc_domain": NotRequired[str],
        "ccev_domain": NotRequired[str],
        "family": NotRequired[str],
        "ft_coiled": NotRequired[str],
        "ftlen_coiled": NotRequired[int],
        "ftev_coiled": NotRequired[str],
        "ft_compbias": NotRequired[str],
        "ftlen_compbias": NotRequired[int],
        "ftev_compbias": NotRequired[str],
        "ft_motif": NotRequired[str],
        "ftlen_motif": NotRequired[int],
        "ftev_motif": NotRequired[str],
        "ft_region": NotRequired[str],
        "ftlen_region": NotRequired[int],
        "ftev_region": NotRequired[str],
        "ft_repeat": NotRequired[str],
        "ftlen_repeat": NotRequired[int],
        "ftev_repeat": NotRequired[str],
        "cc_similarity": NotRequired[str],
        "ccev_similarity": NotRequired[str],
        "ft_zn_fing": NotRequired[str],
        "ftlen_zn_fing": NotRequired[int],
        "ftev_zn_fing": NotRequired[str],
        "xref_any": NotRequired[str],
        "xref_embl": NotRequired[str],
        "xref_ccds": NotRequired[str],
        "xref_pir": NotRequired[str],
        "xref_refseq": NotRequired[str],
        "xref_pdb": NotRequired[str],
        "xref_pdbsum": NotRequired[str],
        "xref_pcddb": NotRequired[str],
        "xref_sasbdb": NotRequired[str],
        "xref_bmrb": NotRequired[str],
        "xref_smr": NotRequired[str],
        "xref_alphafolddb": NotRequired[str],
        "xref_biogrid": NotRequired[str],
        "xref_complexportal": NotRequired[str],
        "xref_corum": NotRequired[str],
        "xref_dip": NotRequired[str],
        "xref_elm": NotRequired[str],
        "xref_intact": NotRequired[str],
        "xref_mint": NotRequired[str],
        "xref_string": NotRequired[str],
        "xref_bindingdb": NotRequired[str],
        "xref_chembl": NotRequired[str],
        "xref_drugbank": NotRequired[str],
        "xref_guidetopharmacology": NotRequired[str],
        "xref_swisslipids": NotRequired[str],
        "xref_drugcentral": NotRequired[str],
        "xref_allergome": NotRequired[str],
        "xref_cazy": NotRequired[str],
        "xref_esther": NotRequired[str],
        "xref_imgt_gene-db": NotRequired[str],
        "xref_merops": NotRequired[str],
        "xref_moondb": NotRequired[str],
        "xref_moonprot": NotRequired[str],
        "xref_clae": NotRequired[str],
        "xref_peroxibase": NotRequired[str],
        "xref_rebase": NotRequired[str],
        "xref_tcdb": NotRequired[str],
        "xref_unilectin": NotRequired[str],
        "xref_carbonyldb": NotRequired[str],
        "xref_depod": NotRequired[str],
        "xref_glyconnect": NotRequired[str],
        "xref_glygen": NotRequired[str],
        "xref_iptmnet": NotRequired[str],
        "xref_phosphositeplus": NotRequired[str],
        "xref_swisspalm": NotRequired[str],
        "xref_unicarbkb": NotRequired[str],
        "xref_metosite": NotRequired[str],
        "xref_biomuta": NotRequired[str],
        "xref_dmdm": NotRequired[str],
        "xref_dbsnp": NotRequired[str],
        "xref_compluyeast-2dpage": NotRequired[str],
        "xref_dosac-cobs-2dpage": NotRequired[str],
        "xref_ogp": NotRequired[str],
        "xref_reproduction-2dpage": NotRequired[str],
        "xref_swiss-2dpage": NotRequired[str],
        "xref_ucd-2dpage": NotRequired[str],
        "xref_world-2dpage": NotRequired[str],
        "xref_cptac": NotRequired[str],
        "xref_epd": NotRequired[str],
        "xref_maxqb": NotRequired[str],
        "xref_paxdb": NotRequired[str],
        "xref_peptideatlas": NotRequired[str],
        "xref_pride": NotRequired[str],
        "xref_promex": NotRequired[str],
        "xref_proteomicsdb": NotRequired[str],
        "xref_topdownproteomics": NotRequired[str],
        "xref_jpost": NotRequired[str],
        "xref_massive": NotRequired[str],
        "xref_dnasu": NotRequired[str],
        "xref_abcd": NotRequired[str],
        "xref_antibodypedia": NotRequired[str],
        "xref_cptc": NotRequired[str],
        "xref_ensembl": NotRequired[str],
        "xref_ensemblbacteria": NotRequired[str],
        "xref_ensemblfungi": NotRequired[str],
        "xref_ensemblmetazoa": NotRequired[str],
        "xref_ensemblplants": NotRequired[str],
        "xref_ensemblprotists": NotRequired[str],
        "xref_geneid": NotRequired[str],
        "xref_gramene": NotRequired[str],
        "xref_kegg": NotRequired[str],
        "xref_mane-select": NotRequired[str],
        "xref_patric": NotRequired[str],
        "xref_ucsc": NotRequired[str],
        "xref_vectorbase": NotRequired[str],
        "xref_wbparasite": NotRequired[str],
        "xref_wbparasitetranscriptprotein": NotRequired[str],
        "xref_arachnoserver": NotRequired[str],
        "xref_araport": NotRequired[str],
        "xref_cgd": NotRequired[str],
        "xref_conoserver": NotRequired[str],
        "xref_ctd": NotRequired[str],
        "xref_dictybase": NotRequired[str],
        "xref_disgenet": NotRequired[str],
        "xref_echobase": NotRequired[str],
        "xref_euhcvdb": NotRequired[str],
        "xref_veupathdb": NotRequired[str],
        "xref_flybase": NotRequired[str],
        "xref_genecards": NotRequired[str],
        "xref_genereviews": NotRequired[str],
        "xref_hgnc": NotRequired[str],
        "xref_hpa": NotRequired[str],
        "xref_legiolist": NotRequired[str],
        "xref_leproma": NotRequired[str],
        "xref_maizegdb": NotRequired[str],
        "xref_malacards": NotRequired[str],
        "xref_mgi": NotRequired[str],
        "xref_mim": NotRequired[str],
        "xref_niagads": NotRequired[str],
        "xref_nextprot": NotRequired[str],
        "xref_opentargets": NotRequired[str],
        "xref_orphanet": NotRequired[str],
        "xref_pharmgkb": NotRequired[str],
        "xref_pombase": NotRequired[str],
        "xref_pseudocap": NotRequired[str],
        "xref_rgd": NotRequired[str],
        "xref_sgd": NotRequired[str],
        "xref_tair": NotRequired[str],
        "xref_tuberculist": NotRequired[str],
        "xref_vgnc": NotRequired[str],
        "xref_wormbase": NotRequired[str],
        "xref_xenbase": NotRequired[str],
        "xref_zfin": NotRequired[str],
        "xref_eggnog": NotRequired[str],
        "xref_genetree": NotRequired[str],
        "xref_hogenom": NotRequired[str],
        "xref_inparanoid": NotRequired[str],
        "xref_ko": NotRequired[str],
        "xref_oma": NotRequired[str],
        "xref_orthodb": NotRequired[str],
        "xref_phylomedb": NotRequired[str],
        "xref_treefam": NotRequired[str],
        "xref_biocyc": NotRequired[str],
        "xref_brenda": NotRequired[str],
        "xref_reactome": NotRequired[str],
        "xref_sabio-rk": NotRequired[str],
        "xref_signalink": NotRequired[str],
        "xref_signor": NotRequired[str],
        "xref_unipathway": NotRequired[str],
        "xref_plantreactome": NotRequired[str],
        "xref_pathwaycommons": NotRequired[str],
        "xref_chitars": NotRequired[str],
        "xref_evolutionarytrace": NotRequired[str],
        "xref_genewiki": NotRequired[str],
        "xref_genomernai": NotRequired[str],
        "xref_phi-base": NotRequired[str],
        "xref_pro": NotRequired[str],
        "xref_pharos": NotRequired[str],
        "xref_rnact": NotRequired[str],
        "xref_biogrid-orcs": NotRequired[str],
        "xref_bgee": NotRequired[str],
        "xref_cleanex": NotRequired[str],
        "xref_collectf": NotRequired[str],
        "xref_expressionatlas": NotRequired[str],
        "xref_genevisible": NotRequired[str],
        "xref_cdd": NotRequired[str],
        "xref_gene3d": NotRequired[str],
        "xref_hamap": NotRequired[str],
        "xref_ideal": NotRequired[str],
        "xref_interpro": NotRequired[str],
        "xref_panther": NotRequired[str],
        "xref_pfam": NotRequired[str],
        "xref_pirsf": NotRequired[str],
        "xref_prints": NotRequired[str],
        "xref_prodom": NotRequired[str],
        "xref_sfld": NotRequired[str],
        "xref_smart": NotRequired[str],
        "xref_supfam": NotRequired[str],
        "xref_tigrfams": NotRequired[str],
        "xref_prosite": NotRequired[str],
        "xref_disprot": NotRequired[str],
        "xref_go": NotRequired[str],
        "xref_proteomes": NotRequired[str],
        "database": NotRequired[str],
        "cc_webresource": NotRequired[str],
        "ccev_webresource": NotRequired[str],
        "date_created": NotRequired[date],
        "date_modified": NotRequired[date],
        "date_sequence_modified": NotRequired[date],
        "go_field": NotRequired[str],
        "go_evidence": NotRequired[str],
        "chebi_field": NotRequired[str],
        "inchikey_field": NotRequired[str],
        "keyword_field": NotRequired[str],
        "lit_author": NotRequired[str],
        "lit_journal": NotRequired[str],
        "lit_pubdate": NotRequired[date],
        "lit_pubmed": NotRequired[str],
        "lit_title": NotRequired[str],
        "lit_citation_id": NotRequired[str],
        "computational_pubmed_id": NotRequired[str],
        "community_pubmed_id": NotRequired[str],
        "proteome": NotRequired[str],
        "proteome_component": NotRequired[str],
        "cited_for": NotRequired[str],
        "reviewed": NotRequired[bool],
        "active": NotRequired[bool],
        "uniref_cluster_50": NotRequired[str],
        "uniref_cluster_90": NotRequired[str],
        "uniref_cluster_100": NotRequired[str],
        "uniparc": NotRequired[str],
    },
)
UniprotkbNamesTaxonomy: TypeAlias = Literal[
    "accession",
    "id",
    "gene_names",
    "gene_oln",
    "gene_orf",
    "gene_primary",
    "gene_synonym",
    "organism_name",
    "organism_id",
    "protein_name",
    "xref_proteomes",
    "lineage",
    "lineage_ids",
    "virus_hosts",
]
UniprotkbSequences: TypeAlias = Literal[
    "cc_alternative_products",
    "ft_var_seq",
    "error_gmodel_pred",
    "fragment",
    "organelle",
    "length",
    "mass",
    "cc_mass_spectrometry",
    "ft_variant",
    "ft_non_cons",
    "ft_non_std",
    "ft_non_ter",
    "cc_polymorphism",
    "cc_rna_editing",
    "sequence",
    "cc_sequence_caution",
    "ft_conflict",
    "ft_unsure",
    "sequence_version",
]
UniprotkbFunction: TypeAlias = Literal[
    "absorption",
    "ft_act_site",
    "ft_binding",
    "ft_ca_bind",
    "cc_catalytic_activity",
    "cc_cofactor",
    "ft_dna_bind",
    "ec",
    "cc_activity_regulation",
    "cc_function",
    "kinetics",
    "ft_metal",
    "ft_np_bind",
    "cc_pathway",
    "ph_dependence",
    "redox_potential",
    "rhea",
    "ft_site",
    "temp_dependence",
]
UniprotkbMiscellaneous: TypeAlias = Literal[
    "annotation_score",
    "cc_caution",
    "keyword",
    "keywordid",
    "cc_miscellaneous",
    "protein_existence",
    "reviewed",
    "tools",
    "uniparc_id",
    "comment_count",
    "feature_count",
]
UniprotkbInteraction: TypeAlias = Literal["cc_interaction", "cc_subunit"]
UniprotkbExpression: TypeAlias = Literal[
    "cc_developmental_stage", "cc_induction", "cc_tissue_specificity"
]
UniprotkbGeneOntologyGo: TypeAlias = Literal["go_p", "go_c", "go", "go_f", "go_id"]
UniprotkbPathologyBiotech: TypeAlias = Literal[
    "cc_allergen",
    "cc_biotechnology",
    "cc_disruption_phenotype",
    "cc_disease",
    "ft_mutagen",
    "cc_pharmaceutical",
    "cc_toxic_dose",
]
UniprotkbSubcellularLocation: TypeAlias = Literal[
    "ft_intramem", "cc_subcellular_location", "ft_topo_dom", "ft_transmem"
]
UniprotkbPtmProcessing: TypeAlias = Literal[
    "ft_chain",
    "ft_crosslnk",
    "ft_disulfid",
    "ft_carbohyd",
    "ft_init_met",
    "ft_lipid",
    "ft_mod_res",
    "ft_peptide",
    "cc_ptm",
    "ft_propep",
    "ft_signal",
    "ft_transit",
]
UniprotkbStructure: TypeAlias = Literal[
    "structure_3d", "ft_strand", "ft_helix", "ft_turn"
]
UniprotkbPublications: TypeAlias = Literal[
    "lit_pubmed_id",
]
UniprotkbDateOf: TypeAlias = Literal[
    "date_created", "date_modified", "date_sequence_modified", "version"
]
UniprotkbFamilyDomains: TypeAlias = Literal[
    "ft_coiled",
    "ft_compbias",
    "cc_domain",
    "ft_domain",
    "ft_motif",
    "protein_families",
    "ft_region",
    "ft_repeat",
    "ft_zn_fing",
]
UniprotkbSequence: TypeAlias = Literal[
    "xref_ccds", "xref_embl", "xref_pir", "xref_refseq"
]
UniprotkbThreedStructure: TypeAlias = Literal[
    "xref_alphafolddb",
    "xref_bmrb",
    "xref_pcddb",
    "xref_pdb",
    "xref_pdbsum",
    "xref_sasbdb",
    "xref_smr",
]
UniprotkbProteinProteinInteraction: TypeAlias = Literal[
    "xref_biogrid",
    "xref_corum",
    "xref_complexportal",
    "xref_dip",
    "xref_elm",
    "xref_intact",
    "xref_mint",
    "xref_string",
]
UniprotkbChemistry: TypeAlias = Literal[
    "xref_bindingdb",
    "xref_chembl",
    "xref_drugbank",
    "xref_drugcentral",
    "xref_guidetopharmacology",
    "xref_swisslipids",
]
UniprotkbProteinFamilygroup: TypeAlias = Literal[
    "xref_allergome",
    "xref_cazy",
    "xref_clae",
    "xref_esther",
    "xref_imgt_gene-db",
    "xref_merops",
    "xref_moondb",
    "xref_moonprot",
    "xref_peroxibase",
    "xref_rebase",
    "xref_tcdb",
    "xref_unilectin",
]
UniprotkbPtm: TypeAlias = Literal[
    "xref_carbonyldb",
    "xref_depod",
    "xref_glyconnect",
    "xref_glygen",
    "xref_metosite",
    "xref_phosphositeplus",
    "xref_swisspalm",
    "xref_unicarbkb",
    "xref_iptmnet",
]
UniprotkbPolymorphismAndMutation: TypeAlias = Literal[
    "xref_biomuta", "xref_dmdm", "xref_dbsnp"
]
UniprotkbTwodGel: TypeAlias = Literal[
    "xref_compluyeast-2dpage",
    "xref_dosac-cobs-2dpage",
    "xref_ogp",
    "xref_reproduction-2dpage",
    "xref_swiss-2dpage",
    "xref_ucd-2dpage",
    "xref_world-2dpage",
]
UniprotkbProteomic: TypeAlias = Literal[
    "xref_cptac",
    "xref_epd",
    "xref_massive",
    "xref_maxqb",
    "xref_pride",
    "xref_paxdb",
    "xref_peptideatlas",
    "xref_promex",
    "xref_proteomicsdb",
    "xref_topdownproteomics",
    "xref_jpost",
]
UniprotkbProtocolsAndMaterials: TypeAlias = Literal[
    "xref_abcd", "xref_antibodypedia", "xref_cptc", "xref_dnasu"
]
UniprotkbGenomeAnnotation: TypeAlias = Literal[
    "xref_ensembl",
    "xref_ensemblbacteria",
    "xref_ensemblfungi",
    "xref_ensemblmetazoa",
    "xref_ensemblplants",
    "xref_ensemblprotists",
    "xref_geneid",
    "xref_gramene",
    "xref_kegg",
    "xref_mane-select",
    "xref_patric",
    "xref_ucsc",
    "xref_vectorbase",
    "xref_wbparasite",
    "xref_wbparasitetranscriptprotein",
]
UniprotkbOrganismSpecific: TypeAlias = Literal[
    "xref_arachnoserver",
    "xref_araport",
    "xref_cgd",
    "xref_ctd",
    "xref_conoserver",
    "xref_disgenet",
    "xref_echobase",
    "xref_flybase",
    "xref_genecards",
    "xref_genereviews",
    "xref_hgnc",
    "xref_hpa",
    "xref_legiolist",
    "xref_leproma",
    "xref_mgi",
    "xref_mim",
    "xref_maizegdb",
    "xref_malacards",
    "xref_niagads",
    "xref_opentargets",
    "xref_orphanet",
    "xref_pharmgkb",
    "xref_pombase",
    "xref_pseudocap",
    "xref_rgd",
    "xref_sgd",
    "xref_tair",
    "xref_tuberculist",
    "xref_veupathdb",
    "xref_vgnc",
    "xref_wormbase",
    "xref_xenbase",
    "xref_zfin",
    "xref_dictybase",
    "xref_euhcvdb",
    "xref_nextprot",
]
UniprotkbPhylogenomic: TypeAlias = Literal[
    "xref_genetree",
    "xref_hogenom",
    "xref_inparanoid",
    "xref_ko",
    "xref_oma",
    "xref_orthodb",
    "xref_phylomedb",
    "xref_treefam",
    "xref_eggnog",
]
UniprotkbEnzymeAndPathway: TypeAlias = Literal[
    "xref_brenda",
    "xref_biocyc",
    "xref_pathwaycommons",
    "xref_plantreactome",
    "xref_reactome",
    "xref_sabio-rk",
    "xref_signor",
    "xref_signalink",
    "xref_unipathway",
]
UniprotkbOther: TypeAlias = Literal[
    "xref_biogrid-orcs",
    "xref_chitars",
    "xref_evolutionarytrace",
    "xref_genewiki",
    "xref_genomernai",
    "xref_phi-base",
    "xref_pro",
    "xref_pharos",
    "xref_rnact",
]
UniprotkbGeneExpression: TypeAlias = Literal[
    "xref_bgee",
    "xref_cleanex",
    "xref_collectf",
    "xref_expressionatlas",
    "xref_genevisible",
]
UniprotkbFamilyAndDomain: TypeAlias = Literal[
    "xref_cdd",
    "xref_disprot",
    "xref_gene3d",
    "xref_hamap",
    "xref_ideal",
    "xref_interpro",
    "xref_panther",
    "xref_pirsf",
    "xref_prints",
    "xref_prosite",
    "xref_pfam",
    "xref_prodom",
    "xref_sfld",
    "xref_smart",
    "xref_supfam",
    "xref_tigrfams",
]
UniprotkbFields: TypeAlias = Literal[
    UniprotkbNamesTaxonomy,
    UniprotkbSequences,
    UniprotkbFunction,
    UniprotkbMiscellaneous,
    UniprotkbInteraction,
    UniprotkbExpression,
    UniprotkbGeneOntologyGo,
    UniprotkbPathologyBiotech,
    UniprotkbSubcellularLocation,
    UniprotkbPtmProcessing,
    UniprotkbStructure,
    UniprotkbPublications,
    UniprotkbDateOf,
    UniprotkbFamilyDomains,
    UniprotkbSequence,
    UniprotkbThreedStructure,
    UniprotkbProteinProteinInteraction,
    UniprotkbChemistry,
    UniprotkbProteinFamilygroup,
    UniprotkbPtm,
    UniprotkbPolymorphismAndMutation,
    UniprotkbTwodGel,
    UniprotkbProteomic,
    UniprotkbProtocolsAndMaterials,
    UniprotkbGenomeAnnotation,
    UniprotkbOrganismSpecific,
    UniprotkbPhylogenomic,
    UniprotkbEnzymeAndPathway,
    UniprotkbOther,
    UniprotkbGeneExpression,
    UniprotkbFamilyAndDomain,
]


@dataclass
class UniprotkbSearch(uniprot_rest.Search):
    dataset: Literal["uniprotkb"] = field(default="uniprotkb", init=False)
    query: UniprotkbQuery
    fields: UniprotkbFields
