name: Test 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-extras

      - uses: pre-commit/action@v3.0.0

      - name: Test with pytest
        run: |
          uv run --extra tests pytest

      - name: Test readme notebook
        run: |
          uv run --extra readme jupyter nbconvert --to markdown README.ipynb

      - name: Test docs build
        run: |
          uv run --extra docs mkdocs build