name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Install compiler
        run: sudo apt-get install build-essential

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python 3.10
        run: uv python install 3.10

      - name: Export dependencies
        run: uv export --extra docs --no-hashes --output-file requirements.txt

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: requirements.txt